CREATE TABLE [dbo].[RequestLog]
(
	[Id] NVARCHAR(50) NOT NULL DEFAULT NEWID(),
	[UserId] NVARCHAR(50) NULL,
	[Position] INTEGER NOT NULL,
	[Result] NVARCHAR(MAX) NOT NULL,
	[Date] DATETIME2(7) NOT NULL DEFAULT GETDATE(),
	CONSTRAINT [PK_RequestLog] PRIMARY KEY ([Id]),
	CONSTRAINT [UQ_RequestLog] UNIQUE ([UserId], [Position]),
	CONSTRAINT [FK_RequestLog_Users_Id] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id]) ON DELETE CASCADE
)
